param(
    [string]$CandidatePath='.\research\data\workplace_organization_candidates.csv',
    [string]$OutputPath='.\research\data\workplace_organization_screening.csv',
    [string]$StatsPath='.\research\data\workplace_organization_screening.stats.json',
    [int]$BodyDistinctTermThreshold=6
)
$ErrorActionPreference='Stop'
$directTerms=@('工作','职场','职业','就业','求职','招聘','面试','简历','入职','转正','升职','晋升','加薪','工资','薪酬','绩效','加班','离职','辞职','跳槽','裁员','失业','创业','自由职业','一人公司','同事','领导','老板','下属','上司','员工','公司','单位','组织','团队','企业','部门','岗位','办公室','体制内','编制','公务员','事业单位','国企','私企','客户','供应商','分工','分功','功劳','汇报','甩锅','背锅','内卷','职业生涯','远程办公')
$rows=@(Import-Csv -LiteralPath ([IO.Path]::GetFullPath($CandidatePath)));$selected=[Collections.Generic.List[object]]::new()
foreach($row in $rows){$tq="{0}`n{1}"-f[string]$row.title,[string]$row.question;$dh=@($directTerms|?{$tq.Contains($_,[StringComparison]::OrdinalIgnoreCase)});$bt=@(([string]$row.bodyHits-split'；')|?{$_}|sort -Unique);$reason=if($dh.Count){'标题或问题直接命中职场组织窄词'}elseif($bt.Count-ge$BodyDistinctTermThreshold){"正文至少命中$BodyDistinctTermThreshold个职场组织词"}else{$null};if(!$reason){continue};$selected.Add([pscustomobject][ordered]@{ordinal=[int]$row.ordinal;id=[string]$row.id;date=[string]$row.date;title=[string]$row.title;url=[string]$row.url;question=[string]$row.question;textLength=[int]$row.textLength;relevanceScore=[int]$row.relevanceScore;screeningReason=$reason;directTerms=($dh-join'；');bodyDistinctTermCount=$bt.Count;bodyTerms=($bt-join'；');categories=[string]$row.categories;thesis=[string]$row.thesis;authorActionAndEthicalJudgments=[string]$row.authorActionAndEthicalJudgments;faithfulSummary=[string]$row.faithfulSummary;sourceReadingFile=[string]$row.sourceReadingFile})}
$sorted=@($selected|sort @{Expression='relevanceScore';Descending=$true},@{Expression='textLength';Descending=$true},ordinal);$sorted|Export-Csv -LiteralPath ([IO.Path]::GetFullPath($OutputPath)) -NoTypeInformation -Encoding utf8BOM;$unique=@($sorted.id|sort -Unique).Count;$direct=@($sorted|? screeningReason -eq '标题或问题直接命中职场组织窄词').Count;$missing=@($sorted|?{[string]::IsNullOrWhiteSpace($_.thesis)-or[string]::IsNullOrWhiteSpace($_.id)}).Count
$stats=[ordered]@{wideCandidates=$rows.Count;screenedCandidates=$sorted.Count;bodyDistinctTermThreshold=$BodyDistinctTermThreshold;directTitleQuestionCandidates=$direct;bodyMultiTermCandidates=$sorted.Count-$direct;uniqueScreenedIds=$unique;missingCoreFields=$missing;status=if($unique-eq$sorted.Count-and$missing-eq0){'PASS'}else{'REVIEW'}};$stats|ConvertTo-Json -Depth 4|Set-Content -LiteralPath ([IO.Path]::GetFullPath($StatsPath)) -Encoding utf8;$stats|ConvertTo-Json -Depth 4;if($stats.status-ne'PASS'){throw 'Workplace screening validation failed.'}
