param(
    [string]$ValidationPath = (Join-Path $PSScriptRoot '..\data\source_quote_validation_all.csv'),
    [string]$EvidencePath = (Join-Path $PSScriptRoot '..\data\author_view_evidence.jsonl'),
    [string]$CorrectionPath = (Join-Path $PSScriptRoot '..\review\quote-corrections-consolidated.csv'),
    [string]$ManualDecisionPath = (Join-Path $PSScriptRoot '..\review\quote-manual-decisions.csv'),
    [string]$OutputPath = (Join-Path $PSScriptRoot '..\data\verified_source_quotes.jsonl')
)

$ErrorActionPreference = 'Stop'
$byId=@{}
foreach($line in [IO.File]::ReadLines([IO.Path]::GetFullPath($EvidencePath))){if($line){$o=$line|ConvertFrom-Json;$byId[$o.id]=$o}}
$groups=@{}
foreach($q in Import-Csv -LiteralPath $ValidationPath){if(-not $groups.ContainsKey($q.id)){$groups[$q.id]=[Collections.Generic.List[object]]::new()};[void]$groups[$q.id].Add($q)}
$corrections=@{};$resolvedKeys=@{};if(Test-Path -LiteralPath $CorrectionPath){foreach($c in Import-Csv -LiteralPath $CorrectionPath){if($c.decision-like'ACCEPTED*'){if(!$corrections.ContainsKey($c.id)){$corrections[$c.id]=[Collections.Generic.List[object]]::new()};[void]$corrections[$c.id].Add([pscustomobject]@{text=$c.verifiedRawSentence;matchType='manual-correction';sourceCandidate=$c.originalUnlocatedQuote});$resolvedKeys["$($c.id)`t$($c.originalUnlocatedQuote)"]=$true}}}
$rejections=@{};$multiCandidateCount=0;$multiSegmentCount=0;$rejectedCount=0
if(Test-Path -LiteralPath $ManualDecisionPath){foreach($c in Import-Csv -LiteralPath $ManualDecisionPath){$key="$($c.id)`t$($c.originalUnlocatedQuote)";$resolvedKeys[$key]=$true;if($c.decision-eq'ACCEPT_MULTI_SEGMENT'){$multiCandidateCount++;foreach($segment in @($c.verifiedSegmentsJson|ConvertFrom-Json)){$multiSegmentCount++;if(!$corrections.ContainsKey($c.id)){$corrections[$c.id]=[Collections.Generic.List[object]]::new()};[void]$corrections[$c.id].Add([pscustomobject]@{text=$segment.text;matchType='manual-multi-segment';sourceCandidate=$c.originalUnlocatedQuote;start=$segment.start;length=$segment.length})}}elseif($c.decision-eq'REJECT_DIRECT_QUOTE'){$rejectedCount++;if(!$rejections.ContainsKey($c.id)){$rejections[$c.id]=[Collections.Generic.List[string]]::new()};[void]$rejections[$c.id].Add($c.originalUnlocatedQuote)}}}
$full=[IO.Path]::GetFullPath($OutputPath);$writer=[IO.StreamWriter]::new($full,$false,[Text.UTF8Encoding]::new($false));$verified=0;$unverified=0;$corrected=0
try{foreach($id in $byId.Keys){$o=$byId[$id];$items=@($groups[$id]);$good=@($items|?{$_.matchType -in @('exact','partial')});$bad=@($items|?{$_.matchType -eq 'missing' -and -not $resolvedKeys.ContainsKey("$id`t$($_.quote)")});$manual=@($corrections[$id]|?{$null -ne $_});$verified+=$good.Count+$manual.Count;$corrected+=$manual.Count;$unverified+=$bad.Count;$verifiedRows=@($good|%{[ordered]@{text=$_.quote;matchType=$_.matchType}})+@($manual|%{[ordered]@{text=$_.text;matchType=$_.matchType;sourceCandidate=$_.sourceCandidate;start=$_.start;length=$_.length}});$record=[ordered]@{ordinal=$o.ordinal;id=$o.id;title=$o.title;date=$o.date;url=$o.url;verifiedQuotes=$verifiedRows;rejectedDirectQuotes=@($rejections[$id]|?{$null-ne$_});unverifiedQuotes=@($bad|%{$_.quote});sourceReadingFile=$o.sourceReadingFile;evidencePolicy='Only raw-text matches and manually located verbatim segments are retained; paraphrased or spliced candidates are explicitly rejected.'};$writer.WriteLine(($record|ConvertTo-Json -Compress -Depth 6))}}finally{$writer.Dispose()}
$stats=[ordered]@{articleCount=$byId.Count;verifiedQuoteCount=$verified;correctionCount=$corrected;multiSegmentCandidateCount=$multiCandidateCount;multiSegmentQuoteCount=$multiSegmentCount;rejectedDirectQuoteCount=$rejectedCount;unverifiedQuoteCount=$unverified;status=if($byId.Count -eq 4050 -and $unverified -eq 0 -and ($multiCandidateCount+$rejectedCount) -eq 71){'PASS'}else{'REVIEW'}};$stats|ConvertTo-Json|Set-Content -LiteralPath ([IO.Path]::ChangeExtension($full,'.stats.json')) -Encoding UTF8;$stats|ConvertTo-Json
